package mx.gob.imss.cit.sci.mssci.accesodatos.constants;

public class SQLIncapacidadConstants {

	private SQLIncapacidadConstants() {}

	public static final String QS_CONSULTA_INCAPACIDADES_ADSCRIPCION = " SELECT caso.cve_id_caso AS IDCASO, pac.nom_nombre_pac AS PACIENTE, pac.nom_apellido_paterno_pac AS PAPELLIDO, pac.nom_apellido_materno_pac AS SAPELLIDO, pac.ref_nss AS NSS, pac.cve_id_paciente AS IDPACIENTE, uni.des_nombre_unidad AS UNIDAD, uni.cve_id_unidad AS IDUNIDAD, caso.num_dias_acumulados AS DIASACUMULADOS, caso.fec_ini_caso AS INICIOCASO, caso.fec_ult_incap_caso AS FINCASO FROM scit_caso caso INNER JOIN scit_paciente pac ON caso.cve_id_paciente = pac.cve_id_paciente INNER JOIN scic_unidad uni ON pac.cve_id_unidad = uni.cve_id_unidad INNER JOIN scit_incapacidad inc ON inc.cve_id_caso = caso.cve_id_caso WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR uni.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR inc.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) GROUP BY uni.cve_id_unidad, inc.cve_id_caso ORDER BY caso.num_dias_acumulados DESC, caso.fec_ini_caso DESC, pac.ref_nss DESC LIMIT ?,? ";

	public static final String QS_CONSULTA_INCAPACIDADES_ADSCRIPCION_ACTIVOS = " SELECT caso.cve_id_caso AS IDCASO, pac.nom_nombre_pac AS PACIENTE, pac.nom_apellido_paterno_pac AS PAPELLIDO, pac.nom_apellido_materno_pac AS SAPELLIDO, pac.ref_nss AS NSS, pac.cve_id_paciente AS IDPACIENTE, uni.des_nombre_unidad AS UNIDAD, uni.cve_id_unidad AS IDUNIDAD, caso.num_dias_acumulados AS DIASACUMULADOS, caso.fec_ini_caso AS INICIOCASO, caso.fec_ult_incap_caso AS FINCASO FROM scit_caso_activos caso INNER JOIN scit_paciente pac ON caso.cve_id_paciente = pac.cve_id_paciente INNER JOIN scic_unidad uni ON pac.cve_id_unidad = uni.cve_id_unidad INNER JOIN scic_delegacion del ON del.cve_id_delegacion = uni.cve_id_delegacion INNER JOIN scit_incapacidad inc ON inc.cve_id_caso = caso.cve_id_caso LEFT JOIN scic_ramo ramo ON ramo.cve_id_ramo = inc.cve_id_ramo WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR del.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR ramo.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) GROUP BY uni.cve_id_unidad, inc.cve_id_caso ORDER BY caso.num_dias_acumulados DESC, caso.fec_ini_caso DESC, pac.ref_nss DESC LIMIT ?,? ";

	public static final String QS_CONSULTA_INCAPACIDADES_ADSCRIPCION_COUNT = " SELECT COUNT(DISTINCT inc.cve_id_caso, uni.cve_id_unidad) AS TOTAL FROM scit_caso caso INNER JOIN scit_paciente pac ON caso.cve_id_paciente = pac.cve_id_paciente INNER JOIN scic_unidad uni ON pac.cve_id_unidad = uni.cve_id_unidad INNER JOIN scit_incapacidad inc ON inc.cve_id_caso = caso.cve_id_caso WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR uni.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR inc.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) ORDER BY caso.num_dias_acumulados DESC ";

	public static final String QS_CONSULTA_INCAPACIDADES_ADSCRIPCION_COUNT_ACTIVOS = " SELECT COUNT(DISTINCT inc.cve_id_caso, uni.cve_id_unidad) AS TOTAL FROM scit_caso_activos caso INNER JOIN scit_paciente pac ON caso.cve_id_paciente = pac.cve_id_paciente INNER JOIN scic_unidad uni ON pac.cve_id_unidad = uni.cve_id_unidad INNER JOIN scic_delegacion del ON del.cve_id_delegacion = uni.cve_id_delegacion INNER JOIN scit_incapacidad inc ON inc.cve_id_caso = caso.cve_id_caso LEFT JOIN scic_ramo ramo ON ramo.cve_id_ramo = inc.cve_id_ramo WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR del.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR ramo.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) ORDER BY caso.num_dias_acumulados DESC ";

	public static final String QS_CONSULTA_INCAPACIDADES_EXPEDICION = " SELECT caso.cve_id_caso as IDCASO, uni.des_nombre_unidad UNIDAD, uni.cve_id_unidad AS IDUNIDAD, pac.nom_nombre_pac AS PACIENTE, pac.nom_apellido_paterno_pac AS PAPELLIDO, pac.nom_apellido_materno_pac AS SAPELLIDO, pac.cve_id_paciente AS IDPACIENTE, pac.ref_nss NSS, pac.cve_id_paciente AS IDPACIENTE, caso.num_dias_acumulados AS DIASACUMULADOS, caso.fec_ini_caso AS INICIOCASO, caso.fec_ult_incap_caso AS FINCASO FROM scit_incapacidad inc INNER JOIN scit_caso caso ON inc.cve_id_caso = caso.cve_id_caso INNER JOIN scic_unidad uni ON uni.cve_id_unidad = inc.cve_id_unidad_expedicion INNER JOIN scit_paciente pac ON pac.cve_id_paciente = caso.cve_id_paciente WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR uni.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR inc.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) GROUP BY uni.cve_id_unidad, inc.cve_id_caso ORDER BY caso.num_dias_acumulados DESC, caso.fec_ini_caso DESC, pac.ref_nss DESC LIMIT ?,?";

	public static final String QS_CONSULTA_INCAPACIDADES_EXPEDICION_ACTIVOS = " SELECT caso.cve_id_caso as IDCASO, uni.des_nombre_unidad UNIDAD, uni.cve_id_unidad AS IDUNIDAD, pac.nom_nombre_pac AS PACIENTE, pac.nom_apellido_paterno_pac AS PAPELLIDO, pac.nom_apellido_materno_pac AS SAPELLIDO, pac.cve_id_paciente AS IDPACIENTE, pac.ref_nss NSS, pac.cve_id_paciente AS IDPACIENTE, caso.num_dias_acumulados AS DIASACUMULADOS, caso.fec_ini_caso AS INICIOCASO, caso.fec_ult_incap_caso AS FINCASO FROM scit_incapacidad inc INNER JOIN scit_caso_activos caso ON inc.cve_id_caso = caso.cve_id_caso INNER JOIN scic_unidad uni ON uni.cve_id_unidad = inc.cve_id_unidad_expedicion INNER JOIN scic_delegacion del ON del.cve_id_delegacion = uni.cve_id_delegacion INNER JOIN scit_paciente pac ON pac.cve_id_paciente = caso.cve_id_paciente LEFT JOIN scic_ramo ramo ON ramo.cve_id_ramo = inc.cve_id_ramo WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR del.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR ramo.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) GROUP BY uni.cve_id_unidad, inc.cve_id_caso ORDER BY caso.num_dias_acumulados DESC, caso.fec_ini_caso DESC, pac.ref_nss DESC LIMIT ?,?";

	public static final String QS_CONSULTA_INCAPACIDADES_EXPEDICION_COUNT = " SELECT COUNT(DISTINCT inc.cve_id_caso, uni.cve_id_unidad) AS TOTAL FROM scit_incapacidad inc INNER JOIN scit_caso caso ON inc.cve_id_caso = caso.cve_id_caso INNER JOIN scic_unidad uni ON uni.cve_id_unidad = inc.cve_id_unidad_expedicion INNER JOIN scit_paciente pac ON pac.cve_id_paciente = caso.cve_id_paciente WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR uni.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR inc.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) ORDER BY caso.num_dias_acumulados DESC ";

	public static final String QS_CONSULTA_INCAPACIDADES_EXPEDICION_COUNT_ACTIVOS = " SELECT COUNT(DISTINCT inc.cve_id_caso, uni.cve_id_unidad) AS TOTAL FROM scit_incapacidad inc INNER JOIN scit_caso_activos caso ON inc.cve_id_caso = caso.cve_id_caso INNER JOIN scic_unidad uni ON uni.cve_id_unidad = inc.cve_id_unidad_expedicion INNER JOIN scic_delegacion del ON del.cve_id_delegacion = uni.cve_id_delegacion INNER JOIN scit_paciente pac ON pac.cve_id_paciente = caso.cve_id_paciente LEFT JOIN scic_ramo ramo ON ramo.cve_id_ramo = inc.cve_id_ramo WHERE caso.cve_id_estado_incapacidad IN (?, ?) AND (? IS NULL OR del.cve_id_delegacion = ?) AND (? IS NULL OR uni.cve_id_unidad = ?) AND (? IS NULL OR ramo.cve_id_ramo = ?) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 1) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR inc.tip_empleado_imss = 0) AND (? IS NULL OR pac.ref_nss = ?) AND (? IS NULL OR pac.ref_curp = ?) AND (? IS NULL OR pac.cve_id_turno = ?) AND (? IS NULL OR pac.num_consultorio = ?) AND (? IS NULL OR pac.nom_nombre_pac = ?) AND (? IS NULL OR pac.nom_apellido_paterno_pac = ?) AND (? IS NULL OR pac.nom_apellido_materno_pac = ?) AND inc.cve_id_incapacidad IN ( SELECT MAX(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) ORDER BY caso.num_dias_acumulados DESC ";

	public static final String QS_CONSULTA_DETALLE_INCAPACIDAD = " SELECT pac.nom_nombre_pac AS PACIENTE, pac.nom_apellido_paterno_pac AS PAPELLIDO, pac.nom_apellido_materno_pac AS SAPELLIDO, pac.ref_nss AS NSS, pac.ref_curp AS CURP, pac.cve_id_paciente AS IDPACIENTE, uni.des_nombre_unidad AS UNIDAD, uni.cve_id_unidad AS IDUNIDAD, pac.num_consultorio AS UMF, tur.des_turno AS TURNO, tur.cve_id_turno AS IDTURNO, ramo.des_ramo AS RAMO, ciuo.des_ciuo AS OCUPACION, ciuo.cve_id_ciuo AS IDOCUPACION, caso.imp_monto_acumulado AS MONTOACUMULADO, inc.ref_diagnostico AS DIAGNOSTICO, cie.cve_cie AS CIE, cie.cve_id_cie AS IDCIE, caso.num_dias_prob_rec AS DPR, inc.cve_matricula_med AS MATMEDICO, inc.cve_reg_patronal AS REGPATRONAL, inc.cve_id_incapacidad as IDINCAPACIDAD, caso.fec_ini_caso AS INICIOCASO, caso.fec_ult_incap_caso AS FINCASO FROM scit_incapacidad inc INNER JOIN scit_caso caso ON inc.cve_id_caso = caso.cve_id_caso INNER JOIN scit_paciente pac ON pac.cve_id_paciente = caso.cve_id_paciente INNER JOIN scic_unidad uni ON uni.cve_id_unidad = pac.cve_id_unidad INNER JOIN scic_delegacion del ON del.cve_id_delegacion = uni.cve_id_delegacion LEFT JOIN scic_ciuo ciuo ON pac.cve_id_ciuo = ciuo.cve_id_ciuo LEFT JOIN scic_turno tur ON tur.cve_id_turno = pac.cve_id_turno LEFT JOIN scic_ramo ramo ON ramo.cve_id_ramo = inc.cve_id_ramo LEFT JOIN scic_cie cie ON cie.cve_id_cie = inc.cve_id_cie WHERE caso.cve_id_caso = ? AND inc.cve_id_incapacidad IN ( SELECT max(cve_id_incapacidad) from scit_incapacidad inc_caso where caso.cve_id_caso = inc_caso.cve_id_caso) ORDER BY caso.num_dias_acumulados DESC, inc.stp_alta_registro DESC LIMIT 1";

	public static final String QS_CONSULTA_PARAMETRO_ULTIMA_CARGA = " SELECT carga.stp_fec_proceso AS ULTIMACARGA FROM scit_bitacora_carga carga ORDER BY carga.stp_fec_proceso DESC LIMIT 1";

	public static final String QS_CONSULTA_ULTIMA_COMENTARIO = " SELECT coment.ref_texto AS COMENTARIO, clas.des_clasificacion AS SITUACIONACTUAL FROM scit_comentario coment INNER JOIN scic_clasificacion clas ON clas.cve_id_clasificacion = coment.cve_id_clasificacion WHERE coment.cve_id_caso = ? ORDER BY coment.stp_fecha_comentario DESC LIMIT 1";

	public static final String QS_CONSULTA_LISTA_INCAPACIDAD = " SELECT uni.des_nombre_unidad AS UNIDAD, inca.ref_folio AS FOLIO, inca.num_dias_autorizados AS DIAS, inca.cve_matricula_med AS MEDICO, inca.stp_fecha_inicio AS FECHAINICIO, inca.stp_fecha_termino AS FECHAFIN, ramo.num_limite AS LIMITE, ramo.cve_id_ramo AS IDRAMO, ramo.des_ramo AS DESCRAMO, uni.num_nivel AS nivel FROM scit_incapacidad inca INNER JOIN scic_unidad uni ON uni.cve_id_unidad = inca.cve_id_unidad_expedicion INNER JOIN scic_ramo ramo ON ramo.cve_id_ramo = inca.cve_id_ramo WHERE inca.cve_id_caso = ? ORDER BY inca.stp_fecha_inicio ASC";

	public static final String QS_CONSULTA_DETALLE_PACIENTE = " SELECT pac.num_consultorio AS CONSULTORIO, pac.cve_id_ciuo AS IDOCUPACION, pac.cve_id_paciente AS IDPACIENTE, pac.cve_id_turno AS IDTURNO FROM scit_paciente pac WHERE pac.cve_id_paciente = ? LIMIT 1 ";

	public static final String QU_ACTUALIZA_PACIENTE = " UPDATE scit_paciente SET num_consultorio = ?, cve_id_ciuo = ? , cve_id_turno = ?, stp_actualiza_registro = NOW(), cve_matricula_actualiza = ? WHERE cve_id_paciente = ? ";

	public static final String QS_CONSULTA_HISTORICO = " SELECT paciente.ref_nss AS nss, paciente.nom_nombre_pac AS nom_paciente, paciente.nom_apellido_paterno_pac AS ap_paterno, paciente.nom_apellido_materno_pac AS ap_materno, unidad_adscripcion.cve_presupuestal_unidad AS unidad_adscripcion, unidad_adscripcion.des_nombre_unidad AS descripcion_unidad_adscripcion, caso.cve_id_caso AS id_caso, estado_caso.des_estado_incapacidad AS estado_caso, incapacidad.cve_id_incapacidad AS id_incapacidad, estado_incapacidad.des_estado_incapacidad AS estado_incapacidad, incapacidad.ref_folio AS folio, incapacidad.stp_fecha_inicio AS fecha_inicio, incapacidad.stp_fecha_termino AS fecha_termino, incapacidad.num_dias_subsidiados AS dias_subsidiados, incapacidad.num_dias_autorizados AS dias_autorizados, incapacidad.num_dias_acumulados AS dias_acumulados, estado_incapacidad.des_estado_incapacidad AS estado_incapacidad, tipo_inca.cve_tipo_incapacidad AS cve_tincapacidad, tipo_inca.des_tipo_incapacidad AS des_tincapacidad, ramo.cve_ramo AS cve_ramo, ramo.des_ramo AS des_ramo, incapacidad.cve_matricula_med AS cve_matricula, unidad_expedicion.cve_presupuestal_unidad AS cve_presupuestal_expedicion, unidad_expedicion.des_nombre_unidad AS des_nombre_expedicion, incapacidad.ref_diagnostico AS des_medica FROM scit_incapacidad incapacidad INNER JOIN scic_unidad unidad_expedicion ON unidad_expedicion.cve_id_unidad = incapacidad.cve_id_unidad_expedicion LEFT JOIN scic_estado_incapacidad estado_incapacidad ON estado_incapacidad.cve_id_estado_incapacidad = incapacidad.cve_id_estado_incapacidad LEFT JOIN scic_tipo_incapacidad tipo_inca ON tipo_inca.cve_id_tipo_incapacidad = incapacidad.cve_id_tipo_incapacidad LEFT JOIN scic_ramo ramo ON ramo.cve_id_ramo = incapacidad.cve_id_ramo INNER JOIN scit_caso caso ON caso.cve_id_caso = incapacidad.cve_id_caso LEFT JOIN scic_estado_incapacidad estado_caso ON estado_caso.cve_id_estado_incapacidad = caso.cve_id_estado_incapacidad INNER JOIN scit_paciente paciente ON paciente.cve_id_paciente = caso.cve_id_paciente INNER JOIN scic_unidad unidad_adscripcion ON unidad_adscripcion.cve_id_unidad = paciente.cve_id_unidad WHERE unidad_adscripcion.cve_id_unidad = ? AND paciente.ref_nss = ? AND (? IS NULL OR paciente.nom_nombre_pac = ?) AND (? IS NULL OR paciente.nom_apellido_paterno_pac = ?) AND (? IS NULL OR paciente.nom_apellido_materno_pac = ?) ORDER BY incapacidad.stp_fecha_inicio DESC LIMIT ?,? ";

	public static final String QS_CONSULTA_HISTORICO_COUNT = " SELECT count(*) AS total_historico FROM scit_incapacidad incapacidad INNER JOIN scic_unidad unidad_expedicion ON unidad_expedicion.cve_id_unidad = incapacidad.cve_id_unidad_expedicion LEFT JOIN scic_estado_incapacidad estado_incapacidad ON estado_incapacidad.cve_id_estado_incapacidad = incapacidad.cve_id_estado_incapacidad LEFT JOIN scic_tipo_incapacidad tipo_inca ON tipo_inca.cve_id_tipo_incapacidad = incapacidad.cve_id_tipo_incapacidad LEFT JOIN scic_ramo ramo ON ramo.cve_id_ramo = incapacidad.cve_id_ramo INNER JOIN scit_caso caso ON caso.cve_id_caso = incapacidad.cve_id_caso LEFT JOIN scic_estado_incapacidad estado_caso ON estado_caso.cve_id_estado_incapacidad = caso.cve_id_estado_incapacidad INNER JOIN scit_paciente paciente ON paciente.cve_id_paciente = caso.cve_id_paciente INNER JOIN scic_unidad unidad_adscripcion ON unidad_adscripcion.cve_id_unidad = paciente.cve_id_unidad WHERE unidad_adscripcion.cve_id_unidad = ? AND paciente.ref_nss = ? AND (? IS NULL OR paciente.nom_nombre_pac = ?) AND (? IS NULL OR paciente.nom_apellido_paterno_pac = ?) AND (? IS NULL OR paciente.nom_apellido_materno_pac = ?) ";

	public static final String QU_ACTUALIZA_CIE_INCAPACIDAD = " UPDATE scit_incapacidad SET cve_id_cie = ?, ref_diagnostico = ?, stp_actualiza_registro = NOW(), cve_matricula_actualiza = ? WHERE cve_id_incapacidad = ? ";

	public static final String QI_AGREGA_NUEVO_DIAGNOSTICO_POR_CIE = " INSERT INTO scit_diagnostico (cve_id_incapacidad, des_medica, cve_matricula_medico, cve_matricula_alta) VALUES (?,?,?,?)";

}
